name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --configuration Release --no-restore
    - name: Test
      run: dotnet test src --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results.trx"
    - name: Publish NuGet artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NuGet package
        path: src/BitFaster.Caching.DependencyInjection/bin/Release/
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: src/BitFaster.Caching.DependencyInjection.UnitTests/TestResults/coverage.info 
    - name: Create _TMP dir
      run: |
        mkdir src/BitFaster.Caching.DependencyInjection.UnitTests/TestResults/_TMP
    - name: Generate unit test report
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
          test_results_path: src/BitFaster.Caching.DependencyInjection.UnitTests/TestResults/results.trx
          report_name: unit_tests
          report_title: Unit Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: bitfaster_caching_dependencyinjection_unit_tests.md
          gist_badge_label: 'UnitTests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}